import React from 'react'
import Navbar from '../Components/Navbar'
import StudentsDataAnalysis from '../Components/StudentsDataAnalysis'

const Dashboard = () => {
  const interests = [
    {
      name: "Ali",
      email: "a@gmail.com",
      age: "21",
      rollnumber: "Bitf20m0X1",
      gender: "Male",
      dob: "2001-02-22",
      city: "Lahore",
      interest: "Blogging",
      subject: "Data Science",
      degree: "Bachelors Degree",
      department: "Information Technology",
      startdate: "2023-5-21",
      enddate: "2023-9-2",
      created:"2023-12-5",
      status:"enrolled"

    },
    {
      name: "Raheem",
      email: "b@gmail.com",
      age: "22",
      rollnumber: "Bitf20m0X2",
      gender: "Male",
      dob: "2000-05-15",
      city: "Lahore",
      interest: "Traveling",
      subject: "Data structues",
      degree: "Bachelors Degree",
      department: "Computer Science",
      startdate: "2023-3-16",
      enddate: "2023-6-4",
      created:"2023-12-4",
      status:"enrolled"

    }, {
      name: "Zubair",
      email: "c@gmail.com",
      age: "20",
      rollnumber: "Bitf20m0X3",
      gender: "Male",
      dob: "2000-1-1",
      city: "Kasoor",
      interest: "Blogging",
      subject: "Data structues",
      degree: "Bachelors Degree",
      department: "Computer Science",
      startdate: "2023-2-15",
      enddate: "2023-6-10",
      created:"2023-12-8",
      status:"enrolled"

    },
    {
      name: "Ayesha",
      email: "d@gmail.com",
      age: "22",
      rollnumber: "Bitf20m0X4",
      gender: "Female",
      dob: "2001-03-29",
      city: "Faisalabad",
      interest: "Blogging",
      subject: "Object Oriented Programming",
      degree: "Bachelors Degree",
      department: "Computer Science",
      startdate: "2023-3-16",
      enddate: "2023-10-22",
      created:"2023-12-23",
      status:"enrolled"

    },
    {
      name: "Ehsan",
      email: "e@gmail.com",
      age: "22",
      rollnumber: "Bitf20m0X5",
      gender: "Male",
      dob: "1998-03-07",
      city: "Lahore",
      interest: "Sports",
      subject: "Mobile App Development",
      degree: "Associate Doctorate",
      department: "Software Engineering",
      startdate: "2023-3-9",
      enddate: "2023-8-11",
      created:"2023-12-22",
      status:"enrolled"

    },
    {
      name: "Najam",
      email: "f@gmail.com",
      age: "21",
      rollnumber: "Bitf20m0X6",
      gender: "Male",
      dob: "2000-04-14",
      city: "Islamabad",
      interest: "Traveling",
      subject: "Operating System",
      degree: "Bachelors Degree",
      department: "Information Technology",
      startdate: "2023-1-18",
      enddate: "2023-5-10",
      created:"2023-11-6",
      status:"enrolled"

    },
    {
      name: "Nomaan",
      email: "g@gmail.com",
      age: "20",
      rollnumber: "Bitf20m0X7",
      gender: "Male",
      dob: "2001-01-25",
      city: "Lahore",
      interest: "Traveling",
      subject: "Data structures",
      degree: "Bachelors Degree",
      department: "Software Engineering",
      startdate: "2023-5-22",
      enddate: "2023-8-11",
      created:"2023-11-24",
      status:"enrolled"

    },
    {
      name: "Ehsan",
      email: "h@gmail.com",
      age: "22",
      rollnumber: "Bitf20m0X8",
      gender: "Male",
      dob: "1998-03-07",
      city: "Lahore",
      interest: "Sports",
      subject: "Mobile App Development",
      degree: "Associate Doctorate",
      department: "Software Engineering",
      startdate: "2023-3-9",
      enddate: "2023-8-11",
      created:"2023-11-21",
      status:"enrolled"

    },
    {
      name: "John",
      email: "john@gmail.com",
      age: "25",
      rollnumber: "Bitf20m0X101",
      gender: "Male",
      dob: "1998-10-15",
      city: "Lahore",
      interest: "Photography",
      subject: "Computer Science",
      degree: "Bachelors Degree",
      department: "Information Technology",
      startdate: "2023-5-21",
      enddate: "2023-9-2",
      created:"2023-12-14",
      status:"enrolled"
    },
    {
      name: "Emily",
      email: "emily@gmail.com",
      age: "24",
      rollnumber: "Bitf20m0X102",
      gender: "Female",
      dob: "1999-03-22",
      city: "Lahore",
      interest: "Reading",
      subject: "English Literature",
      degree: "Bachelors Degree",
      department: "Humanities",
      startdate: "2023-3-16",
      enddate: "2023-6-4",
      created:"2023-12-28",
      status:"enrolled"
    },
    {
      name: "Carlos",
      email: "carlos@gmail.com",
      age: "23",
      rollnumber: "Bitf20m0X103",
      gender: "Male",
      dob: "2000-01-10",
      city: "Lahore",
      interest: "Photography",
      subject: "Music Production",
      degree: "Bachelors Degree",
      department: "Fine Arts",
      startdate: "2023-2-15",
      enddate: "2023-6-10",
      created:"2023-12-17",
      status:"enrolled"
    },
    {
      name: "Sophie",
      email: "sophie@gmail.com",
      age: "22",
      rollnumber: "Bitf20m0X104",
      gender: "Female",
      dob: "2001-07-29",
      city: "Karachi",
      interest: "Coding",
      subject: "Computer Engineering",
      degree: "M.Phill Degree",
      department: "Engineering",
      startdate: "2023-3-16",
      enddate: "2023-10-22",
      created:"2023-11-25",
      status:"currently studying"
    },
    {
      name: "Daniel",
      email: "daniel@gmail.com",
      age: "24",
      rollnumber: "Bitf20m0X105",
      gender: "Male",
      dob: "1998-12-07",
      city: "Karachi",
      interest: "Sports",
      subject: "Kinesiology",
      degree: "Associate Doctorate",
      department: "Sports Science",
      startdate: "2023-3-9",
      enddate: "2023-8-11",
      created:"2023-12-18",
      status:"currently studying"
    },
    {
      name: "Olivia",
      email: "olivia@gmail.com",
      age: "25",
      rollnumber: "Bitf20m0X106",
      gender: "Female",
      dob: "1999-11-14",
      city: "Karachi",
      interest: "Traveling",
      subject: "Geography",
      degree: "Bachelors Degree",
      department: "Social Sciences",
      startdate: "2023-1-18",
      enddate: "2023-5-10",
      created:"2023-11-15",
      status:"currently studying"
    },
    {
      name: "Noah",
      email: "noah@gmail.com",
      age: "23",
      rollnumber: "Bitf20m0X107",
      gender: "Male",
      dob: "2001-04-25",
      city: "Karachi",
      interest: "Art",
      subject: "Fine Arts",
      degree: "Bachelor of Arts",
      department: "Fine Arts",
      startdate: "2023-5-22",
      enddate: "2023-8-11",
      created:"2023-12-15",
      status:"currently studying"
    },
    {
      name: "Mia",
      email: "mia@gmail.com",
      age: "22",
      rollnumber: "Bitf20m0X108",
      gender: "Female",
      dob: "1998-09-03",
      city: "Karachi",
      interest: "Writing",
      subject: "Creative Writing",
      degree: "Bachelors Degree",
      department: "Humanities",
      startdate: "2023-3-9",
      enddate: "2023-8-11",
      created:"2023-11-13",
      status:"currently studying"
    },
    {
      name: "Liam",
      email: "liam@gmail.com",
      age: "26",
      rollnumber: "Bitf20m0X109",
      gender: "Male",
      dob: "1997-06-18",
      city: "Islamabad",
      interest: "Coding",
      subject: "Computer Science",
      degree: "M.Phill Degree",
      department: "Information Technology",
      startdate: "2023-4-15",
      enddate: "2023-10-30",
      created:"2023-12-5",
      status:"currently studying"
    },
    {
      name: "Ava",
      email: "ava@gmail.com",
      age: "21",
      rollnumber: "Bitf20m0X110",
      gender: "Female",
      dob: "2002-02-01",
      city: "Raheem Yar Khan",
      interest: "Blogging",
      subject: "Performing Arts",
      degree: "Bachelors Degree",
      department: "Fine Arts",
      startdate: "2023-2-10",
      enddate: "2023-7-20",
      created:"2023-11-26",
      status:"currently studying"
    },
    {
      name: "Ethan",
      email: "ethan@gmail.com",
      age: "24",
      rollnumber: "Bitf20m0X111",
      gender: "Male",
      dob: "1999-08-12",
      city: "Lahore",
      interest: "Coding",
      subject: "Computer Science",
      degree: "M.Phill Degree",
      department: "Information Technology",
      startdate: "2023-6-5",
      enddate: "2023-11-30",
      created:"2023-12-2",
      status:"currently studying"
    },
    {
      name: "Emma",
      email: "emma@gmail.com",
      age: "23",
      rollnumber: "Bitf20m0X112",
      gender: "Female",
      dob: "2000-05-28",
      city: "Lahore",
      interest: "Reading",
      subject: "English Literature",
      degree: "Bachelors Degree",
      department: "Humanities",
      startdate: "2023-3-16",
      enddate: "2023-6-4",
      created:"2023-8-5",
      status:"currently studying"
    },
    {
      name: "Lucas",
      email: "lucas@gmail.com",
      age: "22",
      rollnumber: "Bitf20m0X113",
      gender: "Male",
      dob: "2001-01-10",
      city: "Lahore",
      interest: "Music",
      subject: "Music Production",
      degree: "Bachelor of Arts",
      department: "Fine Arts",
      startdate: "2023-2-15",
      enddate: "2023-6-10",
      created:"2023-11-15",
      status:"currently studying"
    },
    {
      name: "Aria",
      email: "aria@gmail.com",
      age: "24",
      rollnumber: "Bitf20m0X114",
      gender: "Female",
      dob: "1998-07-29",
      city: "Sheikhu Poora",
      interest: "Coding",
      subject: "Computer Engineering",
      degree: "Bachelors Degree",
      department: "Engineering",
      startdate: "2023-3-16",
      enddate: "2023-10-22",
      created:"2023-12-5",
      status:"currently studying"
    },
    {
      name: "Jackson",
      email: "jackson@gmail.com",
      age: "25",
      rollnumber: "Bitf20m0X115",
      gender: "Male",
      dob: "1999-12-07",
      city: "Raheem Yar Khan",
      interest: "Sports",
      subject: "Kinesiology",
      degree: "Associate Doctorate",
      department: "Sports Science",
      startdate: "2023-3-9",
      enddate: "2023-8-11",
      created:"2023-9-15",
      status:"currently studying"
    },
    {
      name: "Isabella",
      email: "isabella@gmail.com",
      age: "26",
      rollnumber: "Bitf20m0X116",
      gender: "Female",
      dob: "1997-11-14",
      city: "Islamabad",
      interest: "Traveling",
      subject: "Geography",
      degree: "Bachelors Degree",
      department: "Social Sciences",
      startdate: "2023-1-18",
      enddate: "2023-5-10",
      created:"2023-11-15",
      status:"currently studying"
    },
    {
      name: "Mason",
      email: "mason@gmail.com",
      age: "23",
      rollnumber: "Bitf20m0X117",
      gender: "Male",
      dob: "2001-04-25",
      city: "Lahore",
      interest: "Art",
      subject: "Fine Arts",
      degree: "Bachelor of Arts",
      department: "Fine Arts",
      startdate: "2023-5-22",
      enddate: "2023-8-11",
      created:"2023-12-20",
      status:"currently studying"
    },
    {
      name: "Ava",
      email: "ava@gmail.com",
      age: "22",
      rollnumber: "Bitf20m0X118",
      gender: "Female",
      dob: "1998-09-03",
      city: "Lahore",
      interest: "Writing",
      subject: "Creative Writing",
      degree: "Bachelors Degree",
      department: "Humanities",
      startdate: "2023-3-9",
      enddate: "2023-8-11",
      created:"2023-11-27",
      status:"currently studying"
    },
    {
      name: "Liam",
      email: "liam@gmail.com",
      age: "26",
      rollnumber: "Bitf20m0X119",
      gender: "Male",
      dob: "1997-06-18",
      city: "Raheem Yar Khan",
      interest: "Blogging",
      subject: "Computer Science",
      degree: "Bachelors Degree",
      department: "Information Technology",
      startdate: "2023-4-15",
      enddate: "2023-10-30",
      created:"2023-12-30",
      status:"currently studying"
    },
    {
      name: "Aria",
      email: "aria@gmail.com",
      age: "21",
      rollnumber: "Bitf20m0X120",
      gender: "Female",
      dob: "2002-02-01",
      city: "Lahore",
      interest: "Blogging",
      subject: "Performing Arts",
      degree: "Bachelors Degree",
      department: "Fine Arts",
      startdate: "2023-2-10",
      enddate: "2023-7-20",
      created:"2023-11-19",
      status:"currently studying"
    },
    {
      name: "Ethan",
      email: "ethan@gmail.com",
      age: "24",
      rollnumber: "Bitf20m0X121",
      gender: "Male",
      dob: "1999-08-12",
      city: "Sheikhu Poora",
      interest: "Gaming",
      subject: "Computer Science",
      degree: "M.Phill Degree",
      department: "Information Technology",
      startdate: "2023-6-5",
      enddate: "2023-11-30",
      created:"2023-12-10",
      status:"currently studying"
    },
    {
      name: "Emma",
      email: "emma@gmail.com",
      age: "23",
      rollnumber: "Bitf20m0X122",
      gender: "Female",
      dob: "2000-05-28",
      city: "Islamabad",
      interest: "Reading",
      subject: "English Literature",
      degree: "Bachelors Degree",
      department: "Humanities",
      startdate: "2023-3-16",
      enddate: "2023-6-4",
      created:"2023-11-5",
      status:"currently studying"
    },
    {
      name: "Lucas",
      email: "lucas@gmail.com",
      age: "22",
      rollnumber: "Bitf20m0X123",
      gender: "Male",
      dob: "2001-01-10",
      city: "Raheem Yar Khan",
      interest: "Music",
      subject: "Music Production",
      degree: "Bachelor of Arts",
      department: "Fine Arts",
      startdate: "2023-2-15",
      enddate: "2023-6-10",
      created:"2023-11-10",
      status:"currently studying"
    },
    {
      name: "Aria",
      email: "aria@gmail.com",
      age: "24",
      rollnumber: "Bitf20m0X124",
      gender: "Female",
      dob: "1998-07-29",
      city: "Lahore",
      interest: "Coding",
      subject: "Computer Engineering",
      degree: "Bachelors Degree",
      department: "Engineering",
      startdate: "2023-3-16",
      enddate: "2023-10-22",
      created:"2023-8-5",
      status:"about to graduate"
    },
    {
      name: "Jackson",
      email: "jackson@gmail.com",
      age: "25",
      rollnumber: "Bitf20m0X125",
      gender: "Male",
      dob: "1999-12-07",
      city: "Sheikhu Poora",
      interest: "Sports",
      subject: "Kinesiology",
      degree: "Associate Doctorate",
      department: "Sports Science",
      startdate: "2023-3-9",
      enddate: "2023-8-11",
      created:"2023-7-5",
      status:"about to graduate"
    },
    {
      name: "Isabella",
      email: "isabella@gmail.com",
      age: "26",
      rollnumber: "Bitf20m0X126",
      gender: "Female",
      dob: "1997-11-14",
      city: "Lahore",
      interest: "Traveling",
      subject: "Geography",
      degree: "Bachelors Degree",
      department: "Social Sciences",
      startdate: "2023-1-18",
      enddate: "2023-5-10",
      created:"2023-5-15",
      status:"about to graduate"
    }
  ]

  return (
    <>
      <Navbar />
      <StudentsDataAnalysis studentsData={interests}/>
    </>
  )
}

export default Dashboard
